name: Install Nginx on Servers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        server_ip:
          - 185.65.120.195
          # Add more server IP addresses as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ tictac-deploykey }}

      - name: Install Nginx on Server
        run: |
          echo "Installing Nginx on server with IP: ${{ matrix.server_ip }}"
          ssh -o StrictHostKeyChecking=no suresh@${{ matrix.server_ip }} 'sudo apt-get update && sudo apt-get install -y nginx'
